"""Know whether the board on disk is generated or hand-edited - and say so.

This project has two legitimate ways to change the hardware:

  GENERATIVE   run populate_schematic.py / generate_board.py / route.py.
               Everything is rebuilt from `board/` and the part tables. Any
               hand edit present at that moment is destroyed - not by policy,
               but because generate_board.py clears every track, via, zone and
               drawing before it starts.

  INCREMENTAL  edit the board or schematic directly, in KiCad or through the
               KiCad MCP. Surgical and fast, and the only sane way to nudge one
               silkscreen label on a frozen board - regenerating for that would
               re-route the whole PCB and hand you a different board to
               re-verify.

Neither is wrong. What is wrong is running the generator on top of hand edits
without knowing they are there, which loses work silently. Nothing in the
project could detect that: netlist_fingerprint.py compares the *schematic's*
connectivity and never looks at the PCB, and validate.ps1 hashes files only
within a single run.

So: after a generator run, record what it produced. Before the next one, check.

    python board_provenance.py --record    # generator just ran, this is clean
    python board_provenance.py --check     # exit 1 if hand edits would be lost
    python board_provenance.py --status    # report, always exit 0

`--check` also refuses while KiCad holds the project open, because a second
writer is how the board was lost on 2026-09-07.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RECORD = HERE / "board-provenance.json"

# The files a generator run rewrites. Everything else in hardware/8ch/ is
# either a source the generator reads or an output that is regenerated anyway.
WATCHED = ["thermocouple_8ch.kicad_pcb", "thermocouple_8ch.kicad_sch", "channel.kicad_sch"]


def digest(path: Path) -> dict:
    data = path.read_bytes()
    return {"sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)}


def snapshot() -> dict:
    out = {}
    for name in WATCHED:
        path = HERE / name
        if not path.is_file():
            raise SystemExit(f"missing: {path}")
        out[name] = digest(path)
    return out


def kicad_locks() -> list[Path]:
    """KiCad writes ~<file>.lck next to a project it has open."""
    return sorted(HERE.glob("~*.lck"))


def load_record() -> dict | None:
    if not RECORD.exists():
        return None
    return json.loads(RECORD.read_text(encoding="utf-8"))


def cmd_record(by: str) -> int:
    RECORD.write_text(json.dumps({
        "note": "Hashes of the board and schematic as the generator last left "
                "them. If the files no longer match, someone edited by hand "
                "and running the generator would destroy that work. See "
                "AGENTS.md rules 8 and 9 and docs/decisions/0012.",
        "recorded": dt.datetime.now().astimezone().isoformat(timespec="seconds"),
        "generated_by": by,
        "files": snapshot(),
    }, indent=1) + "\n", encoding="utf-8")
    print(f"ok    recorded {len(WATCHED)} file(s) as generated by {by}")
    for name, info in snapshot().items():
        print(f"        {name}  {info['sha256'][:16]}...  {info['bytes']:,} bytes")
    return 0


def compare() -> tuple[list[str], list[str]]:
    """Returns (drifted, unchanged) file names."""
    record = load_record()
    if record is None:
        return [], []
    current = snapshot()
    drifted, same = [], []
    for name, info in current.items():
        was = record["files"].get(name)
        (same if was and was["sha256"] == info["sha256"] else drifted).append(name)
    return drifted, same


def cmd_status() -> int:
    locks = kicad_locks()
    if locks:
        print("note  KiCad has this project open:")
        for lock in locks:
            print(f"        {lock.name}")

    record = load_record()
    if record is None:
        print("note  no provenance recorded yet - run --record after a "
              "generator run, or treat the board as hand-maintained")
        return 0

    drifted, same = compare()
    print(f"note  last generator run: {record['recorded']} "
          f"({record['generated_by']})")
    for name in same:
        print(f"ok    {name} unchanged since then")
    for name in drifted:
        print(f"DRIFT {name} has been edited since then")
    if drifted:
        print("\n      The board is hand-maintained right now. Running the "
              "generator would discard those edits.")
    return 0


def cmd_check() -> int:
    problems = 0

    locks = kicad_locks()
    if locks:
        print("FAIL  KiCad has the project open - close it before writing the "
              "board.")
        for lock in locks:
            print(f"        {lock.name}")
        print("      Two writers is how the board was lost on 2026-09-07. "
              "This script will not close KiCad for you: it may be holding "
              "unsaved work.")
        problems += 1

    record = load_record()
    if record is None:
        print("FAIL  no board-provenance.json. The board's origin is unknown, "
              "so a generator run cannot be proved safe.")
        print("      If the board really is generator output, run --record.")
        return 1

    drifted, _ = compare()
    if drifted:
        print("FAIL  hand edits would be destroyed by a generator run:")
        for name in drifted:
            print(f"        {name}")
        print(f"      Recorded {record['recorded']} by "
              f"{record['generated_by']}.")
        print("      Either fold the edits back into board/ and the part "
              "tables, or accept losing them and re-run --record first.")
        problems += 1

    if problems:
        return 1
    print("ok    board matches its last generator run; regenerating is safe")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--record", action="store_true",
                       help="store the current hashes as generator output")
    group.add_argument("--check", action="store_true",
                       help="refuse if a generator run would lose hand edits")
    group.add_argument("--status", action="store_true",
                       help="report, without failing")
    parser.add_argument("--by", default="generate_board.py",
                        help="what produced this state (with --record)")
    args = parser.parse_args(argv[1:])

    if args.record:
        return cmd_record(args.by)
    if args.check:
        return cmd_check()
    return cmd_status()


if __name__ == "__main__":
    sys.exit(main(sys.argv))
